"""
Claude AI Signal Validator
--------------------------
Uses the Claude API to validate trading signals before execution.
Claude analyzes recent price action and explains its decision in plain language.

Set ANTHROPIC_API_KEY in your environment or .env file to enable.
Falls back to passthrough (always approve) if not configured.
"""
import json
import logging
from dataclasses import dataclass
from typing import Optional

import pandas as pd

from .config import AIConfig
from .strategies.base import Signal, StrategyResult

logger = logging.getLogger(__name__)


@dataclass
class AIValidation:
    approved: bool
    confidence: float        # 0.0 – 1.0
    reasoning: str
    risk_notes: str = ""
    skipped: bool = False    # True when AI is disabled or unavailable


class AISignalValidator:
    """
    Wraps every strategy signal through Claude before acting on it.
    Claude sees the last N candles and the proposed trade, then decides:
      - approve / reject
      - confidence score
      - plain-language reasoning

    Uses claude-haiku-4-5 for speed and low cost (~$0.001 per validation).
    """

    SYSTEM_PROMPT = """You are a professional crypto trading analyst assistant.
Your job is to validate trading signals generated by technical indicators.

You will receive:
1. Recent OHLCV price data (last 20 candles)
2. A proposed BUY or SELL signal with the indicator reason

You must respond with a JSON object — no markdown, no explanation outside the JSON:
{
  "approved": true | false,
  "confidence": 0.0 to 1.0,
  "reasoning": "1-2 sentence explanation of your decision",
  "risk_notes": "Any specific risks or caveats (can be empty string)"
}

Approve the signal if the price action supports it. Reject if:
- The signal appears to be a false breakout
- There is clear resistance/support against the direction
- Volatility seems dangerously elevated
- The recent trend strongly contradicts the signal

Be decisive. Don't overthink. Low confidence (< 0.5) means reject."""

    def __init__(self, config: AIConfig):
        self.cfg = config
        self._client = None

        if config.enabled and config.api_key:
            try:
                import anthropic
                self._client = anthropic.Anthropic(api_key=config.api_key)
                logger.info(f"AI Validator enabled — model: {config.model}")
            except ImportError:
                logger.warning("anthropic package not installed. Run: pip install anthropic")
        else:
            logger.info("AI Validator disabled (no ANTHROPIC_API_KEY). Signals pass through automatically.")

    @property
    def is_enabled(self) -> bool:
        return self._client is not None

    def validate(
        self,
        symbol: str,
        signal: StrategyResult,
        df: pd.DataFrame,
        current_price: float,
    ) -> AIValidation:
        """
        Validate a BUY/SELL signal using Claude.
        Returns AIValidation(skipped=True) if AI is disabled.
        """
        if not self.is_enabled:
            return AIValidation(approved=True, confidence=1.0, reasoning="AI disabled — passthrough", skipped=True)

        if signal.signal == Signal.HOLD:
            return AIValidation(approved=False, confidence=1.0, reasoning="HOLD signal — no action needed", skipped=True)

        try:
            return self._call_claude(symbol, signal, df, current_price)
        except Exception as e:
            logger.warning(f"AI validation failed ({e}), approving signal by default")
            return AIValidation(
                approved=True,
                confidence=0.5,
                reasoning=f"AI unavailable ({type(e).__name__}) — signal approved by default",
                skipped=True,
            )

    def _call_claude(
        self,
        symbol: str,
        signal: StrategyResult,
        df: pd.DataFrame,
        current_price: float,
    ) -> AIValidation:
        """Make the actual Claude API call."""
        recent = df.tail(20)[["open", "high", "low", "close", "volume"]].copy()
        recent = recent.round(4)

        # Format price data compactly
        candle_lines = []
        for ts, row in recent.iterrows():
            ts_str = ts.strftime("%m-%d %H:%M") if hasattr(ts, 'strftime') else str(ts)
            candle_lines.append(
                f"{ts_str} | O:{row['close']:.2f} H:{row['high']:.2f} "
                f"L:{row['low']:.2f} C:{row['close']:.2f} V:{row['volume']:.0f}"
            )

        price_data = "\n".join(candle_lines)

        # Calculate quick stats for context
        closes = recent["close"]
        price_change_pct = (closes.iloc[-1] - closes.iloc[0]) / closes.iloc[0] * 100
        high_20 = recent["high"].max()
        low_20 = recent["low"].min()

        user_message = f"""Symbol: {symbol}
Current Price: {current_price:.4f}
Proposed Signal: {signal.signal.value.upper()}
Strategy Reason: {signal.reason}
Strategy Confidence: {signal.confidence:.2f}

20-Candle Price Summary:
- Change over period: {price_change_pct:+.2f}%
- 20-candle High: {high_20:.4f}
- 20-candle Low: {low_20:.4f}
- Current vs High: {(current_price - high_20) / high_20 * 100:+.2f}%
- Current vs Low: {(current_price - low_20) / low_20 * 100:+.2f}%

Recent Candles (newest last):
{price_data}

Should I {signal.signal.value.upper()} {symbol} at {current_price:.4f}?"""

        response = self._client.messages.create(
            model=self.cfg.model,
            max_tokens=256,
            system=self.SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_message}],
        )

        raw_text = response.content[0].text.strip()

        # Strip markdown fences if present
        if raw_text.startswith("```"):
            raw_text = raw_text.split("```")[1]
            if raw_text.startswith("json"):
                raw_text = raw_text[4:]

        result = json.loads(raw_text)

        approved = bool(result.get("approved", False))
        confidence = float(result.get("confidence", 0.5))
        reasoning = result.get("reasoning", "No reasoning provided")
        risk_notes = result.get("risk_notes", "")

        # Apply threshold
        if confidence < self.cfg.confidence_threshold:
            approved = False
            reasoning += f" [Confidence {confidence:.2f} below threshold {self.cfg.confidence_threshold}]"

        emoji = "✓" if approved else "✗"
        logger.info(
            f"AI [{emoji}] {signal.signal.value.upper()} {symbol} | "
            f"confidence={confidence:.2f} | {reasoning}"
        )
        if risk_notes:
            logger.info(f"AI Risk: {risk_notes}")

        return AIValidation(
            approved=approved,
            confidence=confidence,
            reasoning=reasoning,
            risk_notes=risk_notes,
        )
